[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  mobizt/FirebaseClient
  miguelbalboa/MFRC522
  adafruit/Adafruit Fingerprint Sensor Library
  bogde/HX711
  adafruit/Adafruit VL53L0X
  madhephaestus/ESP32Servo
  bblanchon/ArduinoJson
